import enum
from datetime import UTC, datetime
from typing import TYPE_CHECKING

import sqlalchemy as sa
import sqlalchemy.orm as so

from makeitso.extensions import db

if TYPE_CHECKING:
    from makeitso.models.commit import Commit
    from makeitso.models.stack import Stack


class DeployStatus(enum.Enum):
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    IN_PROGRESS = "In Progress"
    TIMED_OUT = "Timed Out"
    ABORTED = "Aborted"
    CANCELLED = "Cancelled"
    INTERRUPTED = "Interrupted"


class Deploy(db.Model):
    __table_args__ = (
        # At most one running deployment per stack
        sa.Index(
            "uq_deploy_in_progress_stack",
            "stack_id",
            unique=True,
            postgresql_where=sa.text("status = 'IN_PROGRESS'"),
        ),
    )

    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    stack_id: so.Mapped[int] = so.mapped_column(
        sa.ForeignKey("stack.id"), comment="Foreign key to stack table"
    )
    commit_id: so.Mapped[int] = so.mapped_column(
        sa.ForeignKey("commit.id"), comment="Foreign key to commit table"
    )
    since_commit_id: so.Mapped[int | None] = so.mapped_column(
        sa.ForeignKey("commit.id"),
        comment="The deployed commit when this deploy started; null for a stack's first deploy",
    )
    started_at: so.Mapped[datetime] = so.mapped_column(
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        comment="The datetime in UTC that the deploy attempt was started",
    )
    ended_at: so.Mapped[datetime | None] = so.mapped_column(
        sa.DateTime(timezone=True),
        comment="The datetime in UTC that the deploy attempt ended",
    )
    status: so.Mapped[DeployStatus] = so.mapped_column(
        db.Enum(DeployStatus),
        comment="The status of the deploy attempt. Possible values bound by DeployStatus enum.",
    )
    output: so.Mapped[str] = so.mapped_column(
        comment="The raw stdout generated by the deploy attempt"
    )
    deployed_with_bypass: so.Mapped[bool] = so.mapped_column(
        comment="Boolean value indicates if this deploy was created despite failing CI checks"
    )
    deployed_by: so.Mapped[str | None] = so.mapped_column(
        comment="GitHub login of who started the deploy; null when nobody did (continuous deploy)"
    )

    # Two foreign keys point at commit, so each relationship says which one it uses
    commit: so.Mapped[Commit] = so.relationship(back_populates="deploys", foreign_keys=[commit_id])
    since_commit: so.Mapped[Commit | None] = so.relationship(foreign_keys=[since_commit_id])
    stack: so.Mapped[Stack] = so.relationship()

    @property
    def elapsed(self) -> str:
        """How long the deploy ran, or has been running so far"""
        end = self.ended_at or datetime.now(UTC)
        minutes, seconds = divmod(int((end - self.started_at).total_seconds()), 60)
        return f"{minutes}m {seconds:02d}s"
