import enum
from datetime import datetime

import sqlalchemy as sa
import sqlalchemy.orm as so

from makeitso import db


class DeployStatus(enum.Enum):
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    IN_PROGRESS = "In Progress"
    TIMED_OUT = "Timed Out"
    ABORTED = "Aborted"


class Deploy(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    stack_id: so.Mapped[int] = so.mapped_column(
        sa.ForeignKey("stack.id"), comment="Foreign key to stack table"
    )
    commit_id: so.Mapped[int] = so.mapped_column(
        sa.ForeignKey("commit.id"), comment="Foreign key to stack table"
    )
    started_at: so.Mapped[datetime] = so.mapped_column(
        sa.DateTime(timezone=True),
        comment="The datetime in UTC that the deploy attempt was started",
    )
    ended_at: so.Mapped[datetime | None] = so.mapped_column(
        sa.DateTime(timezone=True), comment="The datetime in UTC that the deploy attempt ended"
    )
    status: so.Mapped[DeployStatus] = so.mapped_column(
        db.Enum(DeployStatus),
        comment="The status of the deploy attempt. Possible values bound by DeployStatus enum.",
    )
    output: so.Mapped[str] = so.mapped_column(
        comment="The raw stdout generated by the deploy attempt"
    )
    deployed_with_bypass: so.Mapped[bool] = so.mapped_column(
        comment="Boolean value indicates if this deploy was created by bypassing safeties"
    )
