apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makeitso.fullname" . }}-deploy-worker
  labels:
    component: deploy-worker
{{- include "makeitso.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployWorker.replicas }}
  selector:
    matchLabels:
      {{- include "makeitso.selectorLabels" . | nindent 6 }}
      component: deploy-worker
  template:
    metadata:
      labels:
{{- include "makeitso.selectorLabels" . | nindent 8 }}
        component: deploy-worker
    spec:
      restartPolicy: Always
      serviceAccountName: {{ .Values.deployWorker.serviceAccountName }}
      containers:
        - name: {{ template "makeitso.fullname" . }}-deploy-worker
          image: {{ .Values.app.image }}:{{ .Values.app.imageTag }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          # Syncs have their own worker, see sync-worker-deployment.yaml
          command: ["flask", "--app", "makeitso", "worker", "--queue", "deploys"]
          env:
            {{- include "makeitso.commonEnv" . | nindent 12 }}
            {{- include "makeitso.superuserDbEnv" . | nindent 12 }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.githubAppSecretName | quote }}
                  key: ghToken
            - name: DEPLOY_WORKSPACE
              value: /workspace
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir:
            sizeLimit: 1Gi
