apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makeitso.fullname" . }}-app
  labels:
    component: app
{{- include "makeitso.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "makeitso.selectorLabels" . | nindent 6 }}
      component: app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "makeitso.selectorLabels" . | nindent 8 }}
        component: app
    spec:
      containers:
        - name: {{ template "makeitso.fullname" . }}-app
          image: {{ .Values.app.image }}:{{ .Values.app.imageTag }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: makeitso-db-pguser-postgres
                  key: uri
            - name: REDIS_HOST
              value: redis://{{ include "makeitso.fullname" . }}-redis.{{ .Release.Namespace }}.svc.cluster.local:6379
            - name: GITHUB_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: makeitso-github-app-secret
                  key: clientId
            - name: GITHUB_APP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: makeitso-github-app-secret
                  key: clientSecret
            - name: MAKEITSO_ENV
              value: {{ .Values.app.env | default "prod" }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "makeitso.fullname" . }}-secret
                  key: appSecretKey
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
        - name: {{ template "makeitso.fullname" . }}-worker
          image: {{ .Values.app.image }}:{{ .Values.app.imageTag }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: makeitso-db-pguser-postgres
                  key: uri
            - name: REDIS_URL
              value: redis://{{ include "makeitso.fullname" . }}-redis.{{ .Release.Namespace }}.svc.cluster.local:6379
            - name: MAKEITSO_ENV
              value: {{ .Values.app.env | default "prod" }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "makeitso.fullname" . }}-secret
                  key: appSecretKey
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
          command: ["flask", "--app", "makeitso", "worker"]
      restartPolicy: Always