apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "makeitso.fullname" . }}-app
  labels:
    component: app
{{- include "makeitso.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "makeitso.selectorLabels" . | nindent 6 }}
      component: app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{- include "makeitso.selectorLabels" . | nindent 8 }}
        component: app
    spec:
      containers:
        - name: {{ template "makeitso.fullname" . }}-app
          image: {{ .Values.app.image }}:{{ .Values.app.imageTag }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          env:
            {{- include "makeitso.appEnv" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
      restartPolicy: Always