apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "makeitso.fullname" . }}-redis
  labels:
{{ include "makeitso.labels" . | indent 4 }}
spec:
  storageClassName: netapp-block-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi