{{- $appSecret := (randAlphaNum 60) | b64enc | quote }}
{{- $secretName := print (include "makeitso.fullname" .) "-secret" }}

{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $existingSecret }}
{{- $appSecret = index $existingSecret.data "appSecretKey" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "makeitso.fullname" . }}-secret
  labels: {{ include "makeitso.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  appSecretKey: {{ $appSecret }}
