apiVersion: v1
kind: Service
metadata:
  name: {{ include "makeitso.fullname" . }}
  labels:
    {{- include "makeitso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ include "makeitso.fullname" . }}-port
  selector:
    {{- include "makeitso.selectorLabels" . | nindent 4 }}
    component: app