kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-deployer
  labels: {{ include "makeitso.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - list
      - update
      - watch
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreamimages
      - imagestreammappings
      - imagestreams
      - imagestreamtags
  - verbs:
      - delete
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreamtags
  - verbs:
      - get
    apiGroups:
      - project.openshift.io
      - ''
    resources:
      - projects
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - pods
      - pods/exec
      - replicationcontrollers
      - secrets
      - services
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
      - pods/status
  - verbs:
      - create
      - get
      - patch
      - update
    apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
  - verbs:
      - create
      - delete
      - get
      - patch
      - update
    apiGroups:
      - apps
    resources:
      - statefulsets
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - apps
    resources:
      - deployments/scale
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - create
    apiGroups:
      - template.openshift.io
    resources:
      - processedtemplates
  - verbs:
      - create
      - get
      - patch
      - update
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - create
    apiGroups:
      - route.openshift.io
      - ''
    resources:
      - routes/custom-host
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - batch
    resources:
      - jobs/status
  - verbs:
      - create
      - delete
      - get
      - patch
      - update
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    apiGroups:
      - rbac.authorization.k8s.io
      - authorization.openshift.io
    resources:
      - rolebindings
      - roles
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
  - verbs:
      - get
      - list
    apiGroups:
      - artifactory.devops.gov.bc.ca
    resources:
      - artifactoryserviceaccounts
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
    apiGroups:
      - postgres-operator.crunchydata.com
    resources:
      - postgresclusters
