app:
  image: "ghcr.io/bcgov/makeitso"
  imageTag: "latest"
  imagePullPolicy: Always
  replicas: 1
  env: prod

  githubAppSecretName: makeitso-github-app-secret
  githubOrg: bcgov
  githubTeam: cas-developers

# Runs deploys
deployWorker:
  replicas: 1
  serviceAccountName: cas-provision-makeitso-deployer

# Runs stack syncs
syncWorker:
  replicas: 1

# Every 10 minutes, sync stacks not synced in the last 30 minutes
stackSync:
  schedule: "*/10 * * * *"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

db:
  postgresCluster:
    storageSize: 3Gi
    postgres:
      replicaCount: 2
    pgbouncer:
      replicaCount: 2
    users:
      - name: postgres
        password:
          type: AlphaNumeric
        options: "SUPERUSER"
      - name: makeitso
        databases:
          - makeitso
        password:
          type: AlphaNumeric

route:
  host: "makeitso.apps.silver.devops.gov.bc.ca"
