"""init database

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 17:38:22.461028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False, comment='The organization that this stack belongs to'),
    sa.Column('repository', sa.String(), nullable=False, comment='The repository that this stack deploys from'),
    sa.Column('branch', sa.String(), nullable=False, comment='The branch that this stack deploys from'),
    sa.Column('name', sa.String(), nullable=False, comment='The name of this stack'),
    sa.Column('environment', sa.String(), nullable=False, comment='The environment that this stack should deploy to'),
    sa.Column('locked', sa.Boolean(), nullable=False, comment='Boolean value indicates whether this stack is locked and should not deploy.'),
    sa.Column('lock_reason', sa.String(), nullable=True, comment='The reason this branch was locked'),
    sa.Column('continuous_deploy', sa.Boolean(), nullable=False, comment='Boolean value indicates whether this stack should automatically deploy to the target'),
    sa.Column('allow_failures', sa.JSON(), server_default='[]', nullable=False, comment="Check names from engage.yaml's ci.allow_failures at the branch head, set on sync"),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='The datetime that this stack was archived. If this is null then the stack is active.'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.create_index('uq_stack_active_repo_environment', ['organization', 'repository', 'environment'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))

    op.create_table('commit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False, comment='The sha of the commit'),
    sa.Column('commit_message', sa.String(), nullable=False, comment='The commit message from github'),
    sa.Column('pull_request_number', sa.Integer(), nullable=True, comment='The pull request number that this commit relates to in git'),
    sa.Column('url', sa.String(), nullable=False, comment='The url of the commit on github'),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False, comment='The datetime that the commit was committed'),
    sa.Column('author_name', sa.String(), nullable=False, comment='The git author name of the commit'),
    sa.Column('author_login', sa.String(), nullable=True, comment='The github login of the author, if linked to a github account'),
    sa.Column('author_avatar_url', sa.String(), nullable=True, comment='The github avatar url of the author'),
    sa.Column('author_url', sa.String(), nullable=True, comment='The github profile url of the author'),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stack_id', 'commit_sha', name='uq_commit_stack_sha')
    )
    op.create_table('stack_env_var',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False, comment='The foreign key to the stack table'),
    sa.Column('key', sa.String(), nullable=False, comment='The key portion of the environment variable'),
    sa.Column('value', sa.String(), nullable=False, comment='The value portion of the environment variable'),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commit_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='The name of the check pulled from github'),
    sa.Column('state', sa.String(), nullable=False, comment='The conclusion of the check if finished (success, failure, ...), else its status'),
    sa.Column('html_url', sa.String(), nullable=False, comment='The url to the source of the check'),
    sa.ForeignKeyConstraint(['commit_id'], ['commit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deploy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False, comment='Foreign key to stack table'),
    sa.Column('commit_id', sa.Integer(), nullable=False, comment='Foreign key to commit table'),
    sa.Column('since_commit_id', sa.Integer(), nullable=True, comment="The deployed commit when this deploy started; null for a stack's first deploy"),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='The datetime in UTC that the deploy attempt was started'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='The datetime in UTC that the deploy attempt ended'),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', 'IN_PROGRESS', 'TIMED_OUT', 'ABORTED', name='deploystatus'), nullable=False, comment='The status of the deploy attempt. Possible values bound by DeployStatus enum.'),
    sa.Column('output', sa.String(), nullable=False, comment='The raw stdout generated by the deploy attempt'),
    sa.Column('deployed_with_bypass', sa.Boolean(), nullable=False, comment='Boolean value indicates if this deploy was created despite failing CI checks'),
    sa.Column('deployed_by', sa.String(), nullable=True, comment='GitHub login of who started the deploy; null when nobody did (continuous deploy)'),
    sa.ForeignKeyConstraint(['commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['since_commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deploy', schema=None) as batch_op:
        batch_op.create_index('uq_deploy_in_progress_stack', ['stack_id'], unique=True, postgresql_where=sa.text("status = 'IN_PROGRESS'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deploy', schema=None) as batch_op:
        batch_op.drop_index('uq_deploy_in_progress_stack', postgresql_where=sa.text("status = 'IN_PROGRESS'"))

    op.drop_table('deploy')
    op.drop_table('commit_status')
    op.drop_table('stack_env_var')
    op.drop_table('commit')
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.drop_index('uq_stack_active_repo_environment', postgresql_where=sa.text('archived_at IS NULL'))

    op.drop_table('stack')
    ### Manual drop of enum type
    op.execute('drop type if exists deploystatus')
    # ### end Alembic commands ###
