"""init_database

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 13:54:18.133471

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.String(), nullable=False, comment='The repository that this stack deploys from'),
    sa.Column('branch', sa.String(), nullable=False, comment='The branch that this stack deploys from'),
    sa.Column('name', sa.String(), nullable=False, comment='The name of this stack'),
    sa.Column('environment', sa.String(), nullable=False, comment='The environment that this stack should deploy to'),
    sa.Column('locked', sa.Boolean(), nullable=False, comment='Boolean value indicates whether this stack is locked and should not deploy.'),
    sa.Column('lock_reason', sa.String(), nullable=True, comment='The reason this branch was locked'),
    sa.Column('continuous_deploy', sa.Boolean(), nullable=False, comment='Boolean value indicates whether this stack should automatically deploy to the target'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='The datetime that this stack was archived. If this is null then the stack is active.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False, comment='The sha of the commit'),
    sa.Column('commit_message', sa.String(), nullable=False, comment='The commit message from github'),
    sa.Column('pull_request_number', sa.Integer(), nullable=False, comment='The pull request number that this commit relates to in git'),
    sa.Column('is_latest_deployed', sa.Boolean(), nullable=False, comment='Boolean value indicates if this is the commit that was last successfully deployed'),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stack_env_var',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False, comment='The foreign key to the stack table'),
    sa.Column('key', sa.String(), nullable=False, comment='The key portion of the environment variable'),
    sa.Column('value', sa.String(), nullable=False, comment='The value portion of the environment variable'),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commit_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False, comment='The name of the check pulled from github'),
    sa.Column('conclusion', sa.String(), nullable=False, comment='The conclusion status of the check pulled from github'),
    sa.Column('html_url', sa.String(), nullable=False, comment='The url to the source of the check'),
    sa.ForeignKeyConstraint(['commit_id'], ['commit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deploy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False, comment='Foreign key to stack table'),
    sa.Column('commit_id', sa.Integer(), nullable=False, comment='Foreign key to stack table'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='The datetime in UTC that the deploy attempt was started'),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True, comment='The datetime in UTC that the deploy attempt ended'),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', 'IN_PROGRESS', 'TIMED_OUT', 'ABORTED', name='deploystatus'), nullable=False, comment='The status of the deploy attempt. Possible values bound by DeployStatus enum.'),
    sa.Column('output', sa.String(), nullable=False, comment='The raw stdout generated by the deploy attempt'),
    sa.Column('deployed_with_bypass', sa.Boolean(), nullable=False, comment='Boolean value indicates if this deploy was created by bypassing safeties'),
    sa.ForeignKeyConstraint(['commit_id'], ['commit.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deploy')
    op.drop_table('commit_status')
    op.drop_table('stack_env_var')
    op.drop_table('commit')
    op.drop_table('stack')
    ### Manual drop of enum type
    op.execute('drop type deploystatus')
    # ### end Alembic commands ###
