"""add-org-to-stack

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 14:35:22.128745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(), nullable=False, comment='The organization that this stack belongs to'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.drop_column('organization')

    # ### end Alembic commands ###
