"""add stack sync tracking

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 11:37:32.904084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True, comment='When the last sync with GitHub succeeded; null if none has'))
        batch_op.add_column(sa.Column('sync_failures', sa.Integer(), server_default='0', nullable=False, comment='Syncs that failed in a row; a successful sync resets it'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.drop_column('sync_failures')
        batch_op.drop_column('synced_at')

    # ### end Alembic commands ###
