"""store github commit fields

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 11:16:19.904964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False, comment='The url of the commit on github'))
        batch_op.add_column(sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False, comment='The datetime that the commit was committed'))
        batch_op.add_column(sa.Column('author_name', sa.String(), nullable=False, comment='The git author name of the commit'))
        batch_op.add_column(sa.Column('author_login', sa.String(), nullable=True, comment='The github login of the author, if linked to a github account'))
        batch_op.add_column(sa.Column('author_avatar_url', sa.String(), nullable=True, comment='The github avatar url of the author'))
        batch_op.add_column(sa.Column('author_url', sa.String(), nullable=True, comment='The github profile url of the author'))
        batch_op.alter_column('pull_request_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='The pull request number that this commit relates to in git')
        batch_op.create_unique_constraint('uq_commit_stack_sha', ['stack_id', 'commit_sha'])

    # ### end Alembic commands ###

    # Written by hand: autogenerate would drop and re-add the column, losing its data
    with op.batch_alter_table('commit_status', schema=None) as batch_op:
        batch_op.alter_column('conclusion',
               new_column_name='state',
               existing_type=sa.VARCHAR(),
               existing_nullable=False,
               comment='The conclusion of the check if finished (success, failure, ...), else its status',
               existing_comment='The conclusion status of the check pulled from github')


def downgrade():
    with op.batch_alter_table('commit_status', schema=None) as batch_op:
        batch_op.alter_column('state',
               new_column_name='conclusion',
               existing_type=sa.VARCHAR(),
               existing_nullable=False,
               comment='The conclusion status of the check pulled from github',
               existing_comment='The conclusion of the check if finished (success, failure, ...), else its status')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commit', schema=None) as batch_op:
        batch_op.drop_constraint('uq_commit_stack_sha', type_='unique')
        batch_op.alter_column('pull_request_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='The pull request number that this commit relates to in git')
        batch_op.drop_column('author_url')
        batch_op.drop_column('author_avatar_url')
        batch_op.drop_column('author_login')
        batch_op.drop_column('author_name')
        batch_op.drop_column('committed_at')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
