"""unique active stack per repo and environment

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 13:32:59.131621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.create_index('uq_stack_active_repo_environment', ['organization', 'repository', 'environment'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.drop_index('uq_stack_active_repo_environment', postgresql_where=sa.text('archived_at IS NULL'))

    # ### end Alembic commands ###
