"""empty message

Revision ID: e36e6dc1b69c
Revises: 2ed70e314ec0
Create Date: 2026-09-22 15:57:50.812896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36e6dc1b69c'
down_revision = '2ed70e314ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repository', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('branch', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('environment', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('locked', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('lock_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('continuous_deploy', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.drop_column('archived_at')
        batch_op.drop_column('continuous_deploy')
        batch_op.drop_column('lock_reason')
        batch_op.drop_column('locked')
        batch_op.drop_column('environment')
        batch_op.drop_column('name')
        batch_op.drop_column('branch')
        batch_op.drop_column('repository')

    # ### end Alembic commands ###
