"""empty message

Revision ID: f83a441d199b
Revises: e36e6dc1b69c
Create Date: 2026-09-22 16:01:04.428112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f83a441d199b'
down_revision = 'e36e6dc1b69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.alter_column('archived_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stack', schema=None) as batch_op:
        batch_op.alter_column('archived_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
