name: Build makeitso docker image

on:
  workflow_call:
    inputs:
      docker-image-tag:
        description: "Tag for the Docker image"
        required: false
        type: string
        default: "latest"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Succeed
        run: echo "success!"
